---
name: Go Tests
on:
    workflow_dispatch:
    push:
    pull_request:
env:
    GO_VERSION: ~1.22
jobs:
    gotest-dagger:
        name: Go Tests Daggerized
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ env.GO_VERSION }}
            - name: GoTest
              uses: dagger/dagger-for-github@v5
              with:
                  verb: call
                  module: github.com/Excoriate/daggerverse/gotest@v1.12.1
                  args: run-go-test-sum --src="." --enable-pretty --enable-cache
                  version: 0.11.4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
