---
name: Release
on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+.x'
    workflow_dispatch:
defaults:
    run:
        shell: bash
env:
    GO_VERSION: ~1.22

jobs:
    release-please:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        outputs:
            releases_created: ${{ steps.release.outputs.releases_created }}
            tag_name: ${{ steps.release.outputs.tag_name }}
        steps:
            - name: Checkout
              uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
              with:
                  fetch-depth: 0
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  command: manifest
                  token: ${{secrets.GITHUB_TOKEN}}
                  default-branch: main

    publish-go-module:
        needs: release-please
        runs-on: ubuntu-latest
        if: ${{ needs.release-please.outputs.releases_created }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ env.GO_VERSION }}
            - name: Install dependencies
              run: go mod tidy
            - name: Publish Go module
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: ./scripts/publish-go-module.sh
